### ISSUE TITLE
著手 2018-02-10 詩歌集

### ISSUE THREAD

**Issue by awchjimmy** [the-zion-network/tzn-worship#1]
進度：

- [ ] 歌曲名稱
- [ ] youtubeId
---
- [ ] 001-050
- [ ] 051-100
- [ ] 101-150
- [ ] 151-200
- [ ] 201-

**Comment by awchjimmy** [comment]
```yaml
---
20180210-VP:
-
  title:
  youtubeId:
-
  title: 起來榮耀
  youtubeId: w190HBulPJ4
-
  title: 將天敞開
  youtubeId: OVUPLFLdmpE
-
  title: 何等尊貴
  youtubeId: LoZmJyKZITk
-
  title: 以馬內利
  youtubeId: 6hZyvnJn-R4
-
  title: 我的榮耀
  youtubeId:
-
  title:

```
